### ISSUE TITLE
Gym wrappers don't work with CompilerGym version 0.1.10

### ISSUE THREAD

**Issue by phesse001** [facebookresearch/CompilerGym#389]
When I upgraded to version 0.1.10 of CompilerGym, the compiler gym environment no longer worked with the gym wrappers.

## To Reproduce

1.) upgrade to compiler_gym version 0.1.10
2.) wrap compiler gym env with any gym wrapper
The gym wrapper I to implement the patience logic is here:
https://github.com/phesse001/compiler-rl/blob/0ca535a2797b98d5a7027aa4e7cab2c02d2387ca/ppo/cg-rllib.py#L22-L40

### Error Message
```
File "/home/phesse/.local/lib/python3.8/site-packages/compiler_gym/wrappers/core.py", line 42, in step
return self.env.step(action, observations=observations, rewards=rewards)
TypeError: step() got an unexpected keyword argument 'observations'
```
## Expected behavior

The environment would work as modified by the wrapper.

## Environment

Please fill in this checklist:

- CompilerGym: 0.1.10
- How you installed CompilerGym (conda, pip, source): pip
- OS: Ubuntu 20.04
- Python version: 3.8.10

**Comment by ChrisCummins** [comment]
Hi Patrick,

Thanks for reporting this! The issue is that the [compiler_gym.CompilerEnv.step()](https://facebookresearch.github.io/CompilerGym/compiler_gym/envs.html#compiler_gym.envs.CompilerEnv.step) accepts two optional kwargs that `gym.Env.step()` does not. This means that a wrapper class must also accept those kwargs:

```diff
-     def step(self, action):
-         next_state, reward, done, info = self.env.step(action)
+     def step(self, action, **kwargs):
+         next_state, reward, done, info = self.env.step(action, **kwargs)
```

There are other slight differences between `Env` and `CompilerEnv` which need to be handled when wrapping classes. Because of this, CompilerGym ships with [its own set of wrapper base classes](https://facebookresearch.github.io/CompilerGym/compiler_gym/wrappers.html#base-wrappers) that should be used instead of the `gym.wrappers`. I've submitted [a PR](https://github.com/phesse001/compiler-rl/pull/2) to migrate your codebase to these wrappers.

Hope that helps!

Cheers,
Chris

**Comment by phesse001** [comment]
Ahhhh - makes sense, thanks Chris! I guess I probably saw that compiler gym had it's own wrappers but never made the connection as to why. Were these two kwargs not part of 0.1.9?

Thanks for the PR as well, much appreciated!

Patrick

**Comment by ChrisCummins** [comment]
> Were these two kwargs not part of 0.1.9?

Yeah, exactly that. The 0.1.9 release had a bug which meant that those kwargs would be silently ignored. In fixing that bug, I broke compatibility with "regular" gym wrappers.

I'm closing this issue but have made a note to improve the documentation for CompilerGym's wrappers to make this more clear (#394). Thanks again for reporting the issue.

Cheers,
Chris
